=== AEkaterina/CML_2_sem/xml/lab_2/univ_1.dtd
<!DOCTYPE speciality [
<!ELEMENT speciality (university)>
<!ELEMENT university (name, score, plan, city)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT score (#PCDATA)>
<!ELEMENT plan (#PCDATA)>
<!ELEMENT city (#PCDATA)>
]>

=== AEkaterina/CML_2_sem/xml/lab_2/lab2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type = "text/css" href = "style_1.css"?>
<!DOCTYPE speciality SYSTEM "univ_1.dtd">

<speciality>

    <university>
        <name>Белорусский государственный университет информатики и радиоэлектроники</name>
        <score>360 баллов</score>
        <plan>85</plan>
        <city>Минск</city>
    </university>

    <university>
        <name>Белорусский национальный технический университет</name>
        <score>340</score>
        <plan>30</plan>
        <city>Минск</city>
    </university>

    <university>
        <name>Брестский государственный технический университет</name>
        <score>315</score>
        <plan>30</plan>
        <city>Брест</city>
    </university>

    <university>
        <name>Витебский государственный университет имени П.М. Машерова</name>
        <score>311</score>
        <plan>27</plan>
        <city>Витебск</city>
    </university>

    <university>
        <name>Гомельский государственный университет имени Франциска Скорины</name>
        <score>322</score>
        <plan>30</plan>
        <city>Гомель</city>
    </university>
    

</speciality>
